version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /dashboard
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
